feat: add flags
graasp/graasp-app-code-review pull request #72
Opened 2022-02-28 18:10 UTC by spaenleh

Flagged comments are not shown for the moment in the teacher interface.

closes #69

2022-02-28 18:13 UTC, spaenleh commented
@juancarlosfarah sorry for the big PR, this adds general reporting flag functionality as well as bot-only "ask for a human" actions. For now only the "ask for human" are shown to the teacher. The flagged items are not displayed in the teacher view.

In this PR i also correct the position of the Modals to show where the action was made (at the right height).

Here an example of the report dialog:
![Capture d’écran 2022-02-28 à 15 09 02](https://user-images.githubusercontent.com/39373170/156035816-d3cf7bd2-a840-4cb4-b1c7-9b8311ea0b4f.png)

2022-03-01 20:34 UTC, spaenleh commented
Update: Add a view to show flagged comments

2022-04-04 08:47 UTC, juancarlosfarah requested changes
Looks good! Only minor changes!

2022-04-04 08:47 UTC, juancarlosfarah commented on src/langs/en.json
> +    "Please provide bellow the reason for reporting this comment": "Please provide bellow the reason for reporting this comment",
`below`

2022-04-04 08:47 UTC, juancarlosfarah commented on src/components/modes/teacher/TeacherView.js
> +                label={t('Need Help Only')}
Only Show Help Requests

2022-04-04 08:47 UTC, juancarlosfarah commented on src/components/modes/teacher/TeacherView.js
> +      settings: { helpWantedOnly = DEFAULT_HELP_WANTED_ONLY_SETTING },
`helpWanted` => `helpRequestsOnly`

2022-04-04 08:47 UTC, juancarlosfarah commented on src/components/modes/teacher/AvatarDialog.js
> +                  label={t('Allow Human Intervention')}
Maybe allow help requests?

2022-04-04 08:47 UTC, juancarlosfarah commented on src/components/modes/teacher/AvatarDialog.js
> +                  label={t('Allow Human Intervention')}
"Allow Request Human Intervention"

2022-04-04 12:00 UTC, juancarlosfarah approved these changes
👍

2022-04-04 12:01 UTC, merged