feat: add user list to bot settings
graasp/graasp-app-code-review pull request #77
Opened 2022-03-14 16:43 UTC by spaenleh

This PR adds the ability to create a list of users that will see/not see a bot's comments.
The list can be set to "see by default" or "hide by default" so that new users will get the desired visibility without needing to update the list.

![Screenshot 2022-03-14 at 17 40 56](https://user-images.githubusercontent.com/39373170/158219519-937a6b8e-0915-487a-a73d-57601bfa9322.png)

closes #76

2022-03-16 20:22 UTC, juancarlosfarah requested changes
Looking good! Just some minor changes. Also, I wanted to ask if you needed to add anything in the settings reducers. I noticed that because of the conditional in line 606 of CodeReview.js, it should not "hide" if the setting is null, but it might be nice to have the default settings well defined in the reducer.

2022-03-16 20:22 UTC, juancarlosfarah commented on src/components/modes/teacher/AvatarDialog.js
> +    console.log(value);
Remove log.

2022-03-16 20:22 UTC, juancarlosfarah commented on src/components/modes/teacher/AvatarDialog.js
> +    }
Maybe explicitly add a comment when the user is removed and when the user is added, for clarity.

2022-03-17 07:38 UTC, spaenleh commented on src/components/modes/teacher/AvatarDialog.js
> +                  {/* <Grid item>{fileUploadControl}</Grid> */}
Copy-Pasting and forgot to remove

2022-03-17 08:28 UTC, spaenleh commented
@juancarlosfarah I added a merging step before saving the bot settings that will ensure that untouched properties (which were given a default value but were never actually saved in the state get added with their default value before saving the resource).

2022-03-18 21:00 UTC, juancarlosfarah approved these changes
🚀

2022-03-21 08:39 UTC, merged